use have_required()

diff --git a/xs-vlan-create b/xs-vlan-create
--- a/xs-vlan-create
+++ b/xs-vlan-create
@@ -12,6 +12,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 while getopts :p:v:n:d: OPT; do
     case $OPT in
         p)
@@ -32,14 +39,8 @@ while getopts :p:v:n:d: OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
-[ -z "$PIF" ] || [ -z "$VLAN" ] || [ -z "$NETWORK" ] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
+REQUIRED=( "PIF" "VLAN" "NETWORK" )
+have_required "${REQUIRED[@]}" || usage
 
 pif_uuid "$PIF" || exit 1
 echo "PIF UUID: $PIF_UUID"
diff --git a/xs-vm-set-memory b/xs-vm-set-memory
--- a/xs-vm-set-memory
+++ b/xs-vm-set-memory
@@ -5,10 +5,17 @@ function usage() {
 
 Set a VM's memory parameters.
 
-Usage: ${0##*/} [-s STATIC_MIN] [-S STATIC_MAX] [-d DYNAMIC_MIN] [-D DYNAMIC_MAX] -v VM
+Usage: ${0##*/} -s STATIC_MIN -S STATIC_MAX -d DYNAMIC_MIN -D DYNAMIC_MAX -v VM
 EOF
     exit 2
 }
+
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 while getopts :s:S:d:D:v: OPT; do
     case $OPT in
@@ -33,9 +40,8 @@ while getopts :s:S:d:D:v: OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
-[ -z "$VM" ] && usage
-[ -z "$STATIC_MIN" ] && [ -z "$STATIC_MIN" ] && \
-    [ -z "$DYNAMIC_MIN" ] && [ -z "$DYNAMIC_MIN" ] && usage
+REQUIRED=( "STATIC_MIN" "STATIC_MAX" "DYNAMIC_MIN" "DYNAMIC_MAX" "VM" )
+have_required "${REQUIRED[@]}" || usage
 
 VM_UUID=$(xe vm-list name-label="$VM" --minimal)
 if [ -z "$VM_UUID" ]; then
diff --git a/xs-vm-set-vcpu b/xs-vm-set-vcpu
--- a/xs-vm-set-vcpu
+++ b/xs-vm-set-vcpu
@@ -11,6 +11,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 while getopts :m:s:v: OPT; do
     case $OPT in
         m)
@@ -28,14 +35,9 @@ while getopts :m:s:v: OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
-[ -z "$VM" ] || [ -z "$VCPUS_MAX" ] || [ -z "$VCPUS_AT_STARTUP" ] && usage
+REQUIRED=( "VM" "VCPUS_MAX" "VCPUS_AT_STARTUP" )
+have_required "${REQUIRED[@]}" || usage
 
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VM_UUID=$(xe vm-list name-label="$VM" --minimal)
 if [ -z "$VM_UUID" ]; then
