always source xs-functions after arg validation

diff --git a/xs-vif-create b/xs-vif-create
--- a/xs-vif-create
+++ b/xs-vif-create
@@ -12,13 +12,6 @@ EOF
     exit 2
 }
 
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
-
 while getopts :v:n:d:m: OPT; do
     case $OPT in
         v)
@@ -40,6 +33,13 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required VM NETWORK DEVICE || usage
+
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 if [ -n "$MACADDRESS" ]; then
     if ! valid_mac_address "$MACADDRESS"; then
diff --git a/xs-vlan-create b/xs-vlan-create
--- a/xs-vlan-create
+++ b/xs-vlan-create
@@ -1,17 +1,5 @@
 #!/bin/bash
 
-function usage() {
-    cat <<EOF
-Usage: ${0##*/} -p PIF -v VLAN -n NETWORK [-d DESCRIPTION]
-
--p    name label of PIF (physical interface) that supports the desired VLAN
--v    ID (tag) of the new VLAN
--n    name label of the new network
--d    name description of the new network
-EOF
-    exit 2
-}
-
 # get PIF UUID from device name (optional VLAN arg); set global
 # PIF_UUID
 function pif_uuid() {
@@ -27,12 +15,17 @@ function pif_uuid() {
     fi
 }
 
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
+function usage() {
+    cat <<EOF
+Usage: ${0##*/} -p PIF -v VLAN -n NETWORK [-d DESCRIPTION]
+
+-p    name label of PIF (physical interface) that supports the desired VLAN
+-v    ID (tag) of the new VLAN
+-n    name label of the new network
+-d    name description of the new network
+EOF
+    exit 2
+}
 
 while getopts :p:v:n:d: OPT; do
     case $OPT in
@@ -55,6 +48,13 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required PIF VLAN NETWORK || usage
+
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 PIF_UUID=$(pif_uuid "$PIF") || exit 1
 echo "PIF UUID: $PIF_UUID"
diff --git a/xs-vm-set-memory b/xs-vm-set-memory
--- a/xs-vm-set-memory
+++ b/xs-vm-set-memory
@@ -10,13 +10,6 @@ EOF
     exit 2
 }
 
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
-
 while getopts :s:S:d:D:v: OPT; do
     case $OPT in
         s)
@@ -41,6 +34,13 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required STATIC_MIN STATIC_MAX DYNAMIC_MIN DYNAMIC_MAX VM || usage
+
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 VM_UUID=$(get_uuid vm "$VM") || exit 1
 echo "VM UUID: $VM_UUID"
diff --git a/xs-vm-set-vcpu b/xs-vm-set-vcpu
--- a/xs-vm-set-vcpu
+++ b/xs-vm-set-vcpu
@@ -11,13 +11,6 @@ EOF
     exit 2
 }
 
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
-
 while getopts :m:s:v: OPT; do
     case $OPT in
         m)
@@ -36,6 +29,13 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required VM VCPUS_MAX VCPUS_AT_STARTUP || usage
+
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 VM_UUID=$(get_uuid vm "$VM") || exit 1
 echo "VM UUID: $VM_UUID"
