source xs-functions EARLY because some validation/initialization needs it

diff --git a/xs-vdi-destroy-orphans b/xs-vdi-destroy-orphans
--- a/xs-vdi-destroy-orphans
+++ b/xs-vdi-destroy-orphans
@@ -12,6 +12,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 FORCE=0
 
 while getopts :f OPT; do
@@ -25,13 +32,6 @@ while getopts :f OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ $# -gt 0 ] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VDI_UUIDS=$(get_uuids vdi "")
 for VDI_UUID in $VDI_UUIDS; do
diff --git a/xs-vdi-rename-regex b/xs-vdi-rename-regex
--- a/xs-vdi-rename-regex
+++ b/xs-vdi-rename-regex
@@ -1,5 +1,19 @@
 #!/bin/bash
 
+function usage() {
+    cat <<EOF
+
+For VMs that have name labels matching regular expression, set name
+label of VDIs to match VM's name label.
+
+Usage: ${0##*/} [-f] REGEX
+
+-f       set name without prompting
+REGEX    regular expression for matching VM name labels, e.g. '^p[0-9]{5}'
+EOF
+    exit 2
+}
+
 function rename_vdis() {
     [ $# -ne 1 ] && return 2
     local VM_NAME_LABEL="$1" VDI_UUIDS VDI_UUID
@@ -14,19 +28,12 @@ function rename_vdis() {
     return 0
 }
 
-function usage() {
-    cat <<EOF
-
-For VMs that have name labels matching regular expression, set name
-label of VDIs to match VM's name label.
-
-Usage: ${0##*/} [-f] REGEX
-
--f       set name without prompting
-REGEX    regular expression for matching VM name labels, e.g. '^p[0-9]{5}'
-EOF
-    exit 2
-}
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 FORCE=0
 
@@ -43,13 +50,6 @@ done
 shift $(( OPTIND - 1 ))
 [[ -z "$1" || $# -gt 1 ]] && usage
 REGEX="$1"
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 for VM_UUID in $(get_uuids vm ""); do
     echo -e "VM UUID: $VM_UUID"
diff --git a/xs-vif-destroy b/xs-vif-destroy
--- a/xs-vif-destroy
+++ b/xs-vif-destroy
@@ -13,6 +13,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 FORCE=0
 
 while getopts :fv: OPT; do
@@ -29,13 +36,6 @@ while getopts :fv: OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] || [ -z "$VM" ] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VM_UUID=$(get_uuid vm "$VM") || exit 1
 echo "VM UUID: $VM_UUID"
diff --git a/xs-vm-destroy b/xs-vm-destroy
--- a/xs-vm-destroy
+++ b/xs-vm-destroy
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+function usage() {
+    cat <<EOF
+
+Destroy all VMs that have a matching name label.
+
+Usage: ${0##*/} [-f] VM
+
+-f    destroy without prompting
+VM    name label of the VM
+EOF
+    exit 2
+}
+
 function destroy_all() {
     [ $# -ne 1 ] && return 1
     local VM_UUID="$1"
@@ -43,18 +56,12 @@ function destroy_vm() {
     echo "done."
 }
 
-function usage() {
-    cat <<EOF
-
-Destroy all VMs that have a matching name label.
-
-Usage: ${0##*/} [-f] VM
-
--f    destroy without prompting
-VM    name label of the VM
-EOF
-    exit 2
-}
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
 
 FORCE=0
 
@@ -70,13 +77,6 @@ done
 shift $(( OPTIND - 1 ))
 [[ -z "$1" || $# -gt 1 ]] && usage
 VM="$1"
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VM_UUIDS=$(get_uuids vm "$VM")
 if [ -n "$VM_UUIDS" ]; then
diff --git a/xs-vm-hvm-optimize b/xs-vm-hvm-optimize
--- a/xs-vm-hvm-optimize
+++ b/xs-vm-hvm-optimize
@@ -17,6 +17,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 DISABLE=1
 ENABLE=0
 SERIAL=0
@@ -46,13 +53,6 @@ while getopts :ev:spu OPT; do
 done
 shift $(( OPTIND - 1 ))
 [[ $(( SERIAL + PARALLEL + USB )) -eq 0 ]] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VM_UUID=$(get_uuid vm "$VM") || exit 1
 echo "VM UUID: $VM_UUID"
diff --git a/xs-vm-migrate b/xs-vm-migrate
--- a/xs-vm-migrate
+++ b/xs-vm-migrate
@@ -14,6 +14,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 LOCAL=0
 
 while getopts :lh:v: OPT; do
@@ -34,13 +41,6 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required HOST VM || usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 get_uuid host "$HOST" || exit 1
 HOST_UUID="$UUID"
diff --git a/xs-vm-provision-local b/xs-vm-provision-local
--- a/xs-vm-provision-local
+++ b/xs-vm-provision-local
@@ -14,6 +14,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 initialize HOST TEMPLATE VM
 while getopts :h:t:v: OPT; do
     case $OPT in
@@ -33,13 +40,6 @@ done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required TEMPLATE VM || usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 [ -n "$HOST" ] || HOST=$(hostname)
 get_uuid sr "Local storage" host "$HOST" || exit 1
diff --git a/xs-vm-summary b/xs-vm-summary
--- a/xs-vm-summary
+++ b/xs-vm-summary
@@ -14,6 +14,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 SHORT=0
 POOL=0
 DOM0=0
@@ -35,13 +42,6 @@ while getopts :spc OPT; do
 done
 shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 if (( DOM0 )); then
     OPT_STR=""
diff --git a/xs-vm-toggle-template b/xs-vm-toggle-template
--- a/xs-vm-toggle-template
+++ b/xs-vm-toggle-template
@@ -13,6 +13,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 SHOW=0
 
 while getopts :s OPT; do
@@ -27,13 +34,6 @@ done
 shift $(( OPTIND - 1 ))
 [ -z "$1" ] || [ $# -gt 1 ] && usage
 VM="$1"
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 if VM_UUID=$(get_uuid vm "$VM"); then
     if (( SHOW )); then
diff --git a/xs-vm-vdi-rename b/xs-vm-vdi-rename
--- a/xs-vm-vdi-rename
+++ b/xs-vm-vdi-rename
@@ -13,6 +13,13 @@ EOF
     exit 2
 }
 
+MYDIR=$(dirname $0)
+XS_FUNCTIONS="$MYDIR/xs-functions"
+if ! . "$XS_FUNCTIONS"; then
+    echo "Error while sourcing $XS_FUNCTIONS."
+    exit 1
+fi
+
 while getopts :v:n: OPT; do
     case $OPT in
         v)
@@ -29,13 +36,6 @@ shift $(( OPTIND - 1 ))
 [ -n "$1" ] && usage
 have_required VM NAME_LABEL || usage
 [ -z "$VM" ] || [ -z "$NAME_LABEL" ] && usage
-
-MYDIR=$(dirname $0)
-XS_FUNCTIONS="$MYDIR/xs-functions"
-if ! . "$XS_FUNCTIONS"; then
-    echo "Error while sourcing $XS_FUNCTIONS."
-    exit 1
-fi
 
 VM_UUID=$(get_uuid vm "$VM") || exit 1
 echo "VM UUID: $VM_UUID"
